[build-system]
requires = ["setuptools>=64.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scenebuilder"
version = "0.0.1"

[tool.setuptools]
packages = ["scenebuilder", "scenebuilder.core"]

[tool.setuptools.package-dir]
scenebuilder = "."

[tool.setuptools.package-data]
scenebuilder = ["config.yaml", "assets/**/*"]

